// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                  int64
	Email               string
	PasswordHash        string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ConfirmedAt         pgtype.Timestamptz
	ConfirmationToken   pgtype.Text
	ConfirmationSentAt  pgtype.Timestamptz
	ResetPasswordToken  pgtype.Text
	ResetPasswordSentAt pgtype.Timestamptz
}
