package config

var StrengthChallenges = []string{
	"Do 100 push-ups in one session (can be broken into sets)",
	"Complete 40 pull-ups (even if assisted or spread across sets)",
	"Hold a plank for 3 minutes straight",
	"Do 50 burpees in under 5 minutes",
	"Perform 200 squats (bodyweight) in a single session",
	"Achieve 20 consecutive push-ups with perfect form",
	"Complete 10 pistol squats (single-leg squats) on each leg",
	"Perform 5 handstand push-ups (or wall-supported)",
	"Carry two heavy objects (farmer’s walk) for 100 meters without stopping",
	"Do a one-arm push-up on each arm",
	"Hold a weighted plank for 2 minutes",
	"Perform 30 diamond push-ups",
	"Do 15 pull-ups with added weight",
	"Achieve a 2-minute wall sit with weights",
	"Perform 3 sets of 15 Bulgarian split squats per leg",
	"Deadlift 1.5 times your body weight",
	"Bench press your body weight",
	"Perform 50 kettlebell swings in one set",
	"Do 20 tricep dips on parallel bars",
	"Achieve 3 consecutive muscle-ups",
	"Perform a 10-rep max clean and press",
	"Hold a single-leg glute bridge for 1 minute per side",
	"Do 5 sets of 10 jump squats",
	"Perform 100 lunges (50 per leg)",
	"Complete 3 sets of 12 dumbbell shoulder presses",
	"Achieve a 1-rep max squat at 1.5 times body weight",
	"Perform a 2-minute hollow body hold",
	"Do 25 clap push-ups",
	"Perform 10 reps of Nordic hamstring curls",
	"Achieve a 5-second human flag hold",
	"Do 3 sets of 12 pull-up negatives",
	"Perform 3 rounds of 15 goblet squats",
	"Hold a 1-minute L-sit on parallel bars",
	"Complete 3 sets of 10 weighted step-ups",
	"Do 50 push-ups with feet elevated",
	"Perform 20 explosive lunges (jumping switch)",
	"Achieve a 1-minute isometric chin-up hold",
	"Perform 15 slow eccentric pull-ups",
	"Complete 5 rounds of 10 burpee pull-ups",
	"Do 10 archer push-ups per side",
	"Perform 30-second side planks (3 per side)",
	"Complete 3 sets of 12 incline dumbbell presses",
	"Hold a crow pose for 15 seconds",
	"Perform 25 box jumps",
	"Achieve a 30-second hollow back handstand",
	"Do 15 weighted decline sit-ups",
	"Perform a 3-minute farmer's carry",
	"Achieve a front lever hold for 10 seconds",
	"Complete 5 sets of 5 heavy barbell rows",
	"Do 3 sets of 20 leg raises",
}

var EnduranceChallenges = []string{
	"Burn 600+ active calories in a single workout",
	"Run or jog 5 kilometers without stopping",
	"Complete a 10,000-step walk in one session",
	"Cycle for 20 miles or more in one ride",
	"Row on a rowing machine for 10,000 meters",
	"Swim continuously for 1 mile",
	"Complete a 3-minute jump rope session without tripping",
	"Climb 50 flights of stairs in a single workout",
	"Hold a wall sit for 5 minutes straight",
	"Perform a 2,000-meter rowing sprint under 8 minutes",
	"Run a half marathon",
	"Complete 15 minutes of continuous burpees",
	"Swim 500 meters in under 10 minutes",
	"Perform a 30-minute spin session",
	"Run a 10K race",
	"Cycle 50 kilometers in one session",
	"Hike 10 miles with elevation gain",
	"Complete a triathlon (mini or sprint distance)",
	"Perform 10 rounds of 400m runs with 1-minute rest",
	"Do 20 minutes of stair climbing without stopping",
	"Row 5,000 meters in under 20 minutes",
	"Run 3 miles in under 24 minutes",
	"Cycle a century (100 miles) in a day",
	"Perform a 1-hour yoga endurance session",
	"Swim continuously for 30 minutes",
	"Run a mile in under 7 minutes",
	"Do a 45-minute bodyweight endurance circuit",
	"Perform a \"death by burpees\" challenge (1 burpee per minute, increasing each minute until failure)",
	"Complete a 5-mile weighted vest walk",
	"Run 5 miles on a trail",
	"Do 10 rounds of 10 pull-ups, 20 push-ups, and 30 squats",
	"Cycle up a steep hill for 30 minutes",
	"Complete 5 rounds of \"Cindy\" (AMRAP: 5 pull-ups, 10 push-ups, 15 squats in 20 minutes)",
	"Hike for 5 hours without rest",
	"Perform 100 bodyweight squats in under 5 minutes",
	"Complete a 20-minute AMRAP (as many rounds as possible) of 10 burpees, 15 push-ups, and 20 squats",
	"Row 10,000 meters in under 40 minutes",
	"Perform 50 Turkish get-ups in one session",
	"Run a marathon",
	"Complete 100 push-ups, 100 sit-ups, and 100 squats in 30 minutes",
	"Cycle for 2 hours non-stop",
	"Perform a \"300\" workout challenge",
	"Do a Spartan Race or similar obstacle race",
	"Row for 1 hour at a steady pace",
	"Complete a 1,000-calorie workout",
	"Run 8 miles in one session",
	"Do 5 minutes of non-stop mountain climbers",
	"Perform a \"tabata\" endurance workout",
	"Walk 20,000 steps in a single day",
}

var CardioChallenges = []string{
	"Run a mile in under 8 minutes",
	"Perform a HIIT workout for 20 minutes with no breaks longer than 20 seconds",
	"Complete 5 rounds of 20 mountain climbers + 10 burpees",
	"Do 100 jumping jacks in under 2 minutes",
	"Sprint for 1 minute, rest for 1 minute, repeat for 10 rounds",
	"Perform a tabata workout: 20 seconds work, 10 seconds rest for 8 rounds",
	"Do a 3-mile bike sprint as fast as you can",
	"Run 10 intervals of 400 meters with 1-minute rest between each",
	"Perform 30 high knees + 10 push-ups for 10 rounds without stopping",
	"Skip rope for 15 minutes with minimal rest",
	"Complete 50 burpees in under 4 minutes",
	"Run up and down a hill 10 times",
	"Perform a ladder drill for 10 minutes",
	"Sprint 100 meters 10 times with 30-second rests",
	"Do 5 rounds of 15 kettlebell swings + 10 burpees",
	"Run 2 miles in under 16 minutes",
	"Cycle 5 miles in under 20 minutes",
	"Do a 1-minute sprint on the rowing machine, 5 times",
	"Complete a 20-minute stair-climbing workout",
	"Perform 3 rounds of shuttle runs (25m back and forth, 6 times per round)",
	"Do 50 box jumps",
	"Run a 3K time trial",
	"Perform 10 rounds of \"burpee\" tuck jumps",
	"Do 3 rounds of bear crawls for 20 meters",
	"Sprint uphill for 30 seconds, 8 rounds",
	"Perform a 15-minute rowing session at maximum effort",
	"Complete a pyramid workout: 10 burpees, 20 jumping jacks, 30 high knees, 40 mountain climbers, then reverse",
	"Run 1 mile, perform 50 push-ups, then run another mile",
	"Perform a 10-minute shadowboxing session",
	"Cycle as fast as possible for 3 miles",
	"Do a 5-minute tabata workout on the assault bike",
	"Perform 100 kettlebell swings",
	"Run for 30 minutes at a steady pace",
	"Perform 20 broad jumps and sprint back 20 meters, repeat for 5 rounds",
	"Do a circuit: 10 burpees, 20 jump squats, 30 jumping jacks, repeat for 20 minutes",
	"Row for 2,000 meters as fast as possible",
	"Sprint for 20 seconds, walk for 40 seconds, repeat for 15 minutes",
	"Do 50 lateral hops over a bench or line",
	"Perform 5 rounds of \"bear crawls, sprint back\"",
	"Run a 5K race",
	"Complete a 15-minute AMRAP of 10 burpees, 15 kettlebell swings, and 20 squats",
	"Cycle uphill for 15 minutes",
	"Do 10 burpee pull-ups per minute for 5 minutes",
	"Complete a 30-minute fast hike",
	"Do 5 rounds of 15 kettlebell deadlifts and 15 jump squats",
	"Perform 50 air squats followed by a 100-meter sprint, repeat 3 times",
	"Do 10 frog jumps forward, sprint back, repeat 5 times",
	"Row 1,000 meters in under 4 minutes",
}

var CombinationChallenges = []string{
	"Perform a 'Murph' workout: 1-mile run, 100 pull-ups, 200 push-ups, 300 squats, 1-mile run",
	"Burn 1,000 calories in a single day across multiple activities",
	"Complete 100 kettlebell swings in under 5 minutes",
	"Do a circuit: 20 push-ups, 20 squats, 20 burpees, and 20 sit-ups for 3 rounds",
	"Perform 10 pull-ups, 20 push-ups, 30 sit-ups for 5 rounds",
	"Hold a plank for a total of 10 minutes (spread across sets)",
	"Complete a 30-minute bodyweight workout without stopping",
	"Perform 300 reps of mixed movements (e.g., squats, push-ups, burpees)",
	"Work out for 7 days straight without missing a day",
	"Perform a full mobility routine for 30 minutes daily for a week",
	"Run 2 miles, then do 50 squats, 50 push-ups, and 50 burpees",
	"Perform a 15-minute EMOM (Every Minute On the Minute): 10 push-ups, 15 air squats",
	"Complete a Spartan Race or similar obstacle course race",
	"Do a 20-minute yoga flow followed by a 10-minute HIIT session",
	"Perform 5 rounds of \"death by burpees\"",
	"Burn 600 calories in a single workout",
	"Complete a \"fight gone bad\" CrossFit workout",
	"Do a workout with a 20-pound weighted vest",
	"Perform a hero WOD (CrossFit workout of the day)",
	"Complete 100 push-ups, 100 sit-ups, 100 squats in 20 minutes",
	"Run 5 kilometers followed by 30 minutes of mobility work",
	"Perform a 30-minute rowing session followed by 50 kettlebell swings",
	"Complete a \"300\" workout challenge",
	"Do 10 pull-ups, 10 burpees, 10 push-ups, repeat for 15 minutes",
	"Perform 50 kettlebell cleans and presses",
	"Complete a full-body dumbbell circuit: 10 reps per exercise, 3 rounds",
	"Do a 10-minute shadowboxing workout followed by 15 burpees",
	"Perform a \"fight gone bad\" WOD: 3 rounds of wall balls, box jumps, and rowing",
	"Do 100 air squats, 100 push-ups, 100 sit-ups in under 25 minutes",
	"Complete a 60-minute endurance workout: running, rowing, or cycling",
	"Do a 15-minute power yoga session followed by 10 burpees",
	"Perform a 5x5 strength circuit: 5 reps each of deadlifts, squats, and bench press",
	"Complete a workout combining 20 pull-ups, 20 burpees, 20 push-ups, and 20 squats",
	"Run 1 mile, perform 50 pull-ups, run another mile",
	"Perform 5 minutes of continuous kettlebell swings",
	"Do 3 rounds of 10 pull-ups, 20 push-ups, and 30 air squats",
	"Complete a pyramid workout: 5 pull-ups, 10 push-ups, 15 squats, and reverse",
	"Do 100 burpees in under 10 minutes",
	"Run 5 kilometers and perform 5 pull-ups every kilometer",
	"Complete a 20-minute kettlebell workout",
	"Perform 3 rounds of 15 deadlifts, 15 bench presses, and 15 kettlebell swings",
	"Complete a 30-minute workout of 10 burpees, 15 kettlebell swings, and 20 squats",
	"Perform 100 jumping jacks, 100 push-ups, 100 sit-ups, and 100 squats",
	"Run 5 miles and perform 50 squats every mile",
	"Complete a 45-minute bodyweight HIIT session",
	"Do a full-body circuit: 10 pull-ups, 20 push-ups, 30 squats, repeat for 20 minutes",
	"Perform 10 minutes of kettlebell swings followed by 10 burpees",
}
